### ISSUE TITLE
Update fixtures to be more realistic data

### ISSUE THREAD

**Issue by NickLewanowicz** [Kickit/kickit-frontend#4]
## Expected Behavior

The demo app hosted on app.kickit.us should have more realistic data then the random generated data.
## Current Behavior

It's all random words currently
## Possible Solution

Make it less random
## Steps to Reproduce

1. go to the fixture.js file and change the data

**Comment by Foopert** [comment]
Updated fixtures: Now has more realistic data

**Comment by Foopert** [comment]
@NickLewanowicz is this good to be closed now?

**Comment by NickLewanowicz** [comment]
@Foopert  can you link the commit where you fixed this?

**Comment by NickLewanowicz** [comment]
@Foopert fixed in [this commit](https://github.com/Kickit/kickit-frontend/commit/745f99a970fe08f076fec7a84f8d0af03d4824ff) rather then by pr review. 😞

**Comment by NickLewanowicz** [comment]
@Foopert fixed in [this commit](https://github.com/Kickit/kickit-frontend/commit/745f99a970fe08f076fec7a84f8d0af03d4824ff) rather then by pr review. 😞

**Comment by Foopert** [comment]
My apologies, I accidentally pushed to master :(
